version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend/src:/app/src
      - ./backend/db.sqlite:/app/db.sqlite
    depends_on:
      - db

  db:
    image: 'nouchka/sqlite3'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
